LUXOROSH/urls.py
from django.contrib import admin
from django.urls import path,include
from user import urls as user_urls
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(user_urls)),

]

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns+=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path,include
from .views import index,register
from django.contrib.auth.views import (
     LoginView, LogoutView,
)
app_name='user'
urlpatterns = [
    path('', index.as_view(),name="index"),
    path('signup/', register,name="register"),
     path('login/', LoginView.as_view(template_name='user/login.html'), name="login"),
    path('logout/', LogoutView.as_view(template_name='user/logged_out.html'), name="logout"),
]

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.core.exceptions import ValidationError

"""
 Here we are defining four fields namely username, email, password1 and password2; with their own clean_<field_name>() method (except for password1 field).
 Pay close attention to the widget keyword argument in both the password fields. The widget keyword argument allows us to change the default widget of the field.
 Recall that by default, CharField is rendered as text field (i.e <input type="text" ... >).
 To render the CharField as password field we have set widget keyword argument to forms.PasswordInput.

The clean_username() and clean_email() methods check for duplicate username and email respectively.
The clean_password2() method checks whether the password entered in both the fields matches or not. Finally, the save() method saves the data into the database.
"""
class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(label='Enter Username', min_length=4, max_length=150, help_text='Required. Inform a valid email address.')
    email = forms.EmailField(label='Enter email')
    password1 = forms.CharField(label='Enter password', widget=forms.PasswordInput,min_length=8, max_length=16)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput,min_length=8, max_length=16)

    def clean_username(self):
        username = self.cleaned_data['username'].lower()
        r = User.objects.filter(username=username)
        if r.count():
            raise  ValidationError("Username already exists")
        return username

    def clean_email(self):
        email = self.cleaned_data['email'].lower()
        r = User.objects.filter(email=email)
        if r.count():
            raise  ValidationError("Email already exists")
        return email

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')

        if password1 and password2 and password1 != password2:
            raise ValidationError("Password don't match")

        return password2

    def save(self, commit=True):
        user = User.objects.create_user(
            self.cleaned_data['username'],
            self.cleaned_data['email'],
            self.cleaned_data['password1']
        )
        return user

"""
Notice that CustomUserCreationForm inherits from forms.Form class rather than forms.ModelForm.

"""

user/views.py
from django.shortcuts import render,redirect
from django.views.generic import TemplateView

from django.contrib.auth import login, authenticate
from django.contrib import messages
from .forms import CustomUserCreationForm
# Create your views here.
class index(TemplateView):
    template_name='user/index.html'




def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')

            user = authenticate(username=username, password=raw_password)
            login(request, user)
            messages.success(request, 'Account created successfully')
            return redirect('user:index')
        else:
            for msg in form.error_messages:
                print(form.error_messages[msg])
                messages.warning(request,form.error_messages[msg])

            # return render(request = request,
            #               template_name = "user/register.html",
            #               context={"form":form})

    else:
        form = CustomUserCreationForm()
    return render(request=request, template_name='user/register.html', context={'form': form})

templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
    LUXOROSH - {{ block.super }}
      {% endblock %}
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>

  </head>
  <body>
    <header>

    </header>

    <ul class="messages">
      {% for message in messages %}
      <li class="{{ message.tags }}">{{ message }}</li>
    {% endfor %}
    </ul>
    <div class="">
      {% block content %}
      {% endblock %}
    </div>


  </body>
</html>

user/templates/user/index.html
{% block content %}
this is a user/index.html
<hr>
{{request.user.username}}
{% endblock %}

user/templates/user/logged_out.html
{% extends "base.html" %}
{% block content %}
  <div class="container">
      <div class="row justify-content-center align-items-center" style="height:80vh;">
          <div class="col-auto border p-3">
              You are logged out
          </div>
      </div>
  </div>
{% endblock %}

user/templates/user/login.html
{% extends 'base.html' %}
{% block content %}
<h2>login</h2>
 <form method="post" action="{% url 'user:login'%}" >
   {% csrf_token %}
   {% for field in form %}
     <div>
       {{ field.label_tag }}<br>
       {{ field }}
       {% for error in field.errors %}
         <p style="color: red">{{ error }}</p>
       {% endfor %}
     </div>
   {% endfor %}
   <input type="submit" value="login" />
                 <input type="hidden" name="next" value="{{ next }}" />
 </form>
{% endblock %}
<!-- <form method="post" action="{% url 'user:login' %}">
              {% csrf_token %}
              <table>
              <tr>
                  <td>{{ form.username.label_tag }} </td>
                  <td>{{ form.username }}</td>
              </tr>
              <tr>
                  <td>{{ form.password.label_tag }} </td>
                  <td>{{ form.password }}</td>
              </tr>
              </table>
<input type="submit" value="login" />
              <input type="hidden" name="next" value="{{ next }}" />
              </form> -->

user/templates/user/register.html
{% extends 'base.html' %}

{% block content %}
<h2>Sign up</h2>
 <form method="post">
   {% csrf_token %}
   {% for field in form %}
     <div>
       {{ field.label_tag }}<br>
       {{ field }}
       {% for error in field.errors %}
         <p style="color: red">{{ error }}</p>
       {% endfor %}
     </div>
   {% endfor %}
   <button type="submit">Sign up</button>
 </form>
{% endblock %}